site_name: "ML Notebooks"
nav:
  - README.md
  - General:
    - Access Snellius GPUs: gpu.md
    - Practical Information about Data: practical_info_data.md
    - Git Basics: git.md
    - Python Basics: python.md
    - Docker Basics: docker.md
    - Tmux Basics: tmux.md
  - Training and Inference:
    - Training and Inference with Limited Resources: resource_limitations.md
    - Improve Deep Learning Training Results: improve_training_results.md
    - DDP(Distributed Data Parallel in PyTorch: ddp.md
  - Courses and Literature:
    - Courses in Deep Learning and Computer Vision: courses.md
    - Quick Overview of Object Detection: object_detection.md
  - Blogposts:
    - Example Tasks for Large Language, Multimodal, and Vision Models: tasks.md
theme:
  name: material #readthedocs